# Generated by Django 5.2.5 on 2025-10-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_post_likes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='posts/cover'),
        ),
    ]
