# Generated by Django 5.2.5 on 2025-10-20 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginActivity',
        ),
    ]
