# Generated by Django 5.2.5 on 2025-10-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_loginactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_cover_image',
            field=models.FileField(blank=True, null=True, upload_to='profiles/covers'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='profiles/profile'),
        ),
    ]
