# Generated by Django 5.2.5 on 2025-10-21 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_loginactivity_sessionresumetoken_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionResumeToken',
        ),
    ]
