# Generated by Django 5.2.5 on 2025-10-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_delete_sessionresumetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginactivity',
            name='logged_in_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='logged_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
