# Generated by Django 5.2.5 on 2025-10-25 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_profile_cover_image_and_more'),
        ('authentication', '0004_loginactivity_logged_in_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginactivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_activities', to='accounts.userprofile'),
        ),
    ]
